import mysql.connector as msc

db = msc.connect(user="root",passwd="root",auth_plugin='mysql_native_password')
cursor=db.cursor()
def initialize():
    cursor.execute('CREATE DATABASE PHARMACY_MANAGEMENT')
    cursor.execute('USE PHARMACY_MANAGEMENT')
    cursor.execute('CREATE TABLE OWNER(OWNER_ID VARCHAR(20) PRIMARY KEY,PASSWORD VARCHAR(20) )')
    #cursor.execute('CREATE TABLE MANAGER(PASSWORD VARCHAR(15), EMP_ID INT PRIMARY KEY)')
    #cursor.execute('CREATE TABLE PHARMACIST(PASSWORD VARCHAR(15),EMP_ID INT PRIMARY KEY)')
    cursor.execute('CREATE TABLE EMPLOYEE(F_NAME VARCHAR(20) NOT NULL, L_NAME VARCHAR(20), EMP_ID VARCHAR(20) PRIMARY KEY, EMAIL VARCHAR(20), PHONE VARCHAR(20), DOB VARCHAR(20))')
    #cursor.execute('CREATE TABLE PATIENT(P_ID INT NOT NULL, P_NAME VARCHAR(50) NOT NULL, AGE INT NOT NULL, SEX VARCHAR(10) NOT NULL,CONTACT_NUMBER INT NOT NULL,EMAIL VARCHAR(20) NOT NULL, CURRENT_ADDRESS VARCHAR(100) NOT NULL)')
    cursor.execute('CREATE TABLE DRUG(D_ID VARCHAR(20) NOT NULL, D_NAME VARCHAR(50) NOT NULL, SUPPLIER VARCHAR(50) NOT NULL, MANUFACTURER VARCHAR(50) NOT NULL,USES VARCHAR(50) NOT NULL, SIDE_EFFECT VARCHAR(50) NOT NULL)')
    #cursor.execute('CREATE TABLE DRUG_TEMP(D_ID INT NOT NULL, D_NAME VARCHAR(50) NOT NULL, SUPPLIER VARCHAR(50) NOT NULL, MANUFACTURER VARCHAR(50) NOT NULL,USES VARCHAR(50) NOT NULL, SIDE_EFFECT VARCHAR(50) NOT NULL)')
    cursor.execute('CREATE TABLE REQUIREMENT(D_ID VARCHAR(20) NOT NULL,D_NAME VARCHAR(50) NOT NULL, QUANTITY VARCHAR(20) NOT NULL, COST VARCHAR(20) NOT NULL, SUPPLIER VARCHAR(100) NOT NULL, MANUFACTURER VARCHAR(100) NOT NULL)')
    cursor.execute('CREATE TABLE PRESCRIPTION(EMP_ID VARCHAR(20) NOT NULL,PRES_ID VARCHAR(20) NOT NULL, QUANTITY VARCHAR(20) NOT NULL, DOSE VARCHAR(20) NOT NULL,D_ID VARCHAR(20) NOT NULL,D_NAME VARCHAR(50) NOT NULL, P_NAME VARCHAR(100) NOT NULL,PRES_DATE VARCHAR(10) NOT NULL, P_AGE VARCHAR(20) NOT NULL,P_PHONE VARCHAR(10) NOT NULL)')
    cursor.execute('CREATE TABLE MASTER_PRESCRIPTION(DOC_ID VARCHAR(20) NOT NULL,DOC_NAME VARCHAR(50) NOT NULL,P_NAME VARCHAR(100) NOT NULL, PRES_ID VARCHAR(20) NOT NULL, P_AGE VARCHAR(20) NOT NULL,QUANTITY VARCHAR(20) NOT NULL, DOSE VARCHAR(20) NOT NULL,D_NAME VARCHAR(50) NOT NULL, PRES_DATE VARCHAR(10) NOT NULL, P_PHONE VARCHAR(10) NOT NULL)')
    cursor.execute('CREATE TABLE INVOICE(EMP_ID VARCHAR(20) NOT NULL,PRES_ID VARCHAR(20) NOT NULL, QUANTITY VARCHAR(20) NOT NULL, DOSE VARCHAR(20) NOT NULL,D_ID VARCHAR(20) NOT NULL,D_NAME VARCHAR(50) NOT NULL, P_NAME VARCHAR(100) NOT NULL,PRES_DATE VARCHAR(10) NOT NULL, P_AGE VARCHAR(20) NOT NULL,P_PHONE VARCHAR(10) NOT NULL,PRICE VARCHAR(20) NOT NULL)')
    cursor.execute('CREATE TABLE DOCTOR(DOC_ID VARCHAR(20) NOT NULL PRIMARY KEY, DOC_NAME VARCHAR(50) NOT NULL, DOC_ADDRESS VARCHAR(50) NOT NULL,DOC_PHONE VARCHAR(20) NOT NULL)')
    cursor.execute('CREATE TABLE STOCK(D_ID VARCHAR(20) NOT NULL,D_NAME VARCHAR(50) NOT NULL, QUANTITY VARCHAR(20) NOT NULL, COST VARCHAR(20) NOT NULL, SUPPLIER VARCHAR(100) NOT NULL, MANUFACTURER VARCHAR(100) NOT NULL)')
    
    db.commit()
initialize()